version: '3.1'

services:
  mysql-server-8:
    image: 'exahost/mysql8-lastest'
    container_name: mysql-server-8
    restart: always
    ports:
      - 33060:3306
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: DwpESs7751eY

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    links:
      - mysql-server-8:db
    restart: always
    ports:
      - 8080:80

  freeradius:
    image: 'exahost/freeradius3-mysql'
    container_name: freeradius3-mysql
    links:
       - mysql-server-8:db
    restart: always
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
    volumes:
      - "./check-script.sh:/etc/raddb/check-script.sh"
    environment:
      MYSQL_DB: radius
      MYSQL_USER: radius
      MYSQL_USER_PASSWORD: DwpESs7751eY

volumes:
  db_data:
#  radius_conf: